applicationname    = "app1"
location           = "East US 2"
acr_name           = "oogn8ntestacr" # ← The name of your ACR
acr_resource_group = "oog-test-rg"   # ← The resource group where your ACR is
n8n_image_tag      = "latest"
db_admin_username  = "n8nadmin"
db_admin_password  = "Admin@1234321!" # ← The password for your PostgreSQL database admin user. Change this to actual secure password.
costmanagement     = "CostCenter:US31013520+MRU:+LocationCode:+ExpirationDate:"
owner              = "EPRID:- No EPRID -+Name:+Contact:orlando.gutierrez1@hp.com"
environment        = "Development"
